# Generated by Django 2.1.2 on 2018-12-13 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=80)),
                ('sname', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=16)),
                ('category', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('dimg', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150)),
                ('icon', models.CharField(max_length=1000)),
                ('ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.Account')),
            ],
        ),
    ]
